// TripMind CSS keyframes and base styles
export const CSS=[
  "@keyframes spin{to{transform:rotate(360deg)}}",
  "@keyframes fadeUp{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}",
  "@keyframes pulse{0%,100%{opacity:1}50%{opacity:.35}}",
  "@keyframes landingIn{from{opacity:0;transform:translateY(28px)}to{opacity:1;transform:translateY(0)}}",
  "@keyframes landingFade{from{opacity:0}to{opacity:1}}",
  "@keyframes subtitleIn{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}",
  "@keyframes ctaIn{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}",
  ".landing-title{animation:landingIn .9s cubic-bezier(.22,1,.36,1) .35s both}",
  ".landing-sub{animation:subtitleIn .8s cubic-bezier(.22,1,.36,1) .65s both}",
  ".landing-cta{animation:ctaIn .7s cubic-bezier(.22,1,.36,1) .9s both}",
  ".landing-logo{animation:landingFade .8s ease .1s both}",
  ".landing-badge{animation:landingFade .8s ease 1.3s both}",
  ".fu{animation:fadeUp .25s ease forwards}",
  "*{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent}",
  "body{background:#F5EFEB;-webkit-text-size-adjust:100%;font-family:\"FF Real\",\"FF Real Text\",\"FF Real Head\",\"DM Sans\",system-ui,sans-serif;overflow-x:hidden}",
  "input,textarea,select,button{font-family:\"FF Real\",\"FF Real Text\",\"FF Real Head\",\"DM Sans\",system-ui,sans-serif;font-size:16px}",
  "input,textarea,select{font-size:16px!important}",
  "input:focus,textarea:focus,select:focus{outline:2px solid #555;outline-offset:1px}",
  "a{text-decoration:none}",
  "button{cursor:pointer;touch-action:manipulation}",
  "button:active{opacity:.72}",
  ".sx{display:flex;overflow-x:auto;-webkit-overflow-scrolling:touch}",
  ".sx::-webkit-scrollbar{display:none}",
  ".leaflet-container{font-family:\"FF Real\",\"FF Real Text\",\"DM Sans\",system-ui,sans-serif}",
].join("\n");
